In [5]:
import numpy as np

In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [9]:
print(data)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [11]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [13]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [15]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [19]:
data1 = [6, 7.5, 8, 0, 1]

In [21]:
arr1 = np.array(data1)

In [23]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [25]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [27]:
arr2 = np.array(data2)

In [29]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arr2.ndim

2

In [35]:
arr2.shape

(2, 4)

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
np.empty((2,3,2))

array([[[1.13799474e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.03977794e-312, 5.74084271e+169]],

       [[5.24773679e-090, 6.58868291e-066],
        [1.28289407e+160, 2.00562315e-076],
        [6.48224660e+170, 4.93432906e+257]]])

In [43]:
np.empty((2,2))

array([[6. , 7.5],
       [8. , 1. ]])

In [45]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [53]:
arr = np.array([1,2,3,4,5])

In [55]:
arr.dtype

dtype('int32')

In [61]:
float_arr = arr.astype(np.float64)

In [63]:
float_arr

array([1., 2., 3., 4., 5.])

In [65]:
float_arr.dtype

dtype('float64')

In [67]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [69]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [71]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [73]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [77]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [79]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [81]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [83]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [85]:
arr = np.arange(10)

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr[5]

5

In [91]:
arr[5:8]

array([5, 6, 7])

In [93]:
arr[5:8]

array([5, 6, 7])

In [95]:
arr[5:8] = 12

In [97]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [99]:
arr_slice = arr[5:8]

In [101]:
arr_slice

array([12, 12, 12])

In [103]:
arr_slice[1] = 12345

In [105]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [107]:
arr_slice[:] = 64

In [109]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [111]:
arr_slice = arr[5:8].copy()

In [113]:
arr_slice

array([64, 64, 64])

In [115]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [117]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [119]:
arr2d[2]

array([7, 8, 9])

In [123]:
arr2d[0][2]

3

In [125]:
arr2d[0, 2]

3

In [127]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [129]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [131]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
old_values = arr3d[0].copy()

In [135]:
arr3d[0] = 42

In [137]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [139]:
arr3d[0] = old_values

In [141]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [143]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [145]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [147]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [149]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [155]:
lower_dim_slice = arr2d[1, :2]

In [157]:
lower_dim_slice.shape

(2,)

In [159]:
arr2d[:2, 2]

array([3, 6])

In [161]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [163]:
arr2[:2, 1:] = 0

In [165]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [171]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [173]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [175]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [177]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [179]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [181]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [183]:
data[names == "Bob", 1]

array([7, 0])

In [185]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [187]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [189]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [191]:
cond = names == "Bob"

In [193]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [195]:
mask = (names == "Bob") | (names == "Will")

In [197]:
mask

array([ True, False,  True,  True,  True, False, False])

In [199]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [201]:
data[data < 0] = 0

In [203]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [205]:
data[names != "Joe"] = 7

In [207]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [209]:
arr = np.zeros((8, 4))

In [213]:
for i in range(8):
    arr[i] = i

In [215]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [217]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [219]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [221]:
arr = np.arange(32).reshape((8, 4))

In [223]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [225]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [227]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [229]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [231]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [233]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [235]:
arr = np.arange(15).reshape((3, 5))

In [237]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [239]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [243]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])

In [245]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [249]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [251]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [257]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [255]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [260]:
samples = np.random.standard_normal(size=(4, 4))

In [262]:
samples

array([[-0.71331775, -2.4211278 , -0.78069186, -0.63223249],
       [-0.11084965, -0.05767557, -1.52094569,  1.22830219],
       [ 1.8660802 ,  0.3896063 , -1.65258105, -0.2929301 ],
       [-1.22082372,  0.28063336, -2.24175515,  0.51013689]])

In [266]:
arr = np.arange(10)

In [268]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [270]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [272]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
rng = np.random.default_rng()

In [280]:
x = rng.standard_normal(8)

In [282]:
y = rng.standard_normal(8)

In [284]:
x

array([-1.06929947,  0.3830497 ,  0.15277696,  0.65048364, -0.13169384,
       -0.43887276, -0.79137376,  0.36298703])

In [286]:
y

array([ 1.03451512,  1.36511113, -0.54023169, -3.06742396,  1.18220188,
       -1.09920495,  1.21954697,  0.89955522])

In [288]:
np.maximum(x, y)

array([ 1.03451512,  1.36511113,  0.15277696,  0.65048364,  1.18220188,
       -0.43887276,  1.21954697,  0.89955522])

In [290]:
arr = rng.standard_normal(7) * 5

In [292]:
arr

array([ 5.61630013,  1.46949499, -5.54857713, -3.58799502,  0.03646435,
        1.45503847,  2.80795439])

In [294]:
remainder, whole_part = np.modf(arr)

In [296]:
remainder

array([ 0.61630013,  0.46949499, -0.54857713, -0.58799502,  0.03646435,
        0.45503847,  0.80795439])

In [298]:
whole_part

array([ 5.,  1., -5., -3.,  0.,  1.,  2.])

In [300]:
arr

array([ 5.61630013,  1.46949499, -5.54857713, -3.58799502,  0.03646435,
        1.45503847,  2.80795439])

In [302]:
out = np.zeros_like(arr)

In [304]:
np.add(arr, 1)

array([ 6.61630013,  2.46949499, -4.54857713, -2.58799502,  1.03646435,
        2.45503847,  3.80795439])

In [306]:
np.add(arr, 1, out=out)

array([ 6.61630013,  2.46949499, -4.54857713, -2.58799502,  1.03646435,
        2.45503847,  3.80795439])

In [308]:
out

array([ 6.61630013,  2.46949499, -4.54857713, -2.58799502,  1.03646435,
        2.45503847,  3.80795439])

In [312]:
points = np.arange(-5, 5, 0.01)

In [316]:
xs, ys = np.meshgrid(points, points)

In [318]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [320]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [322]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [9]:
import matplotlib.pyplot as plt

In [11]:
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5,-5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

NameError: name 'z' is not defined

In [1]:
plt.close("all")

NameError: name 'plt' is not defined

In [7]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [13]:
result = np.where(cond, xarr, yarr)

In [15]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [19]:
arr = rng.standard_normal((4,4))

In [21]:
arr

array([[-1.72590478,  0.29536096,  0.49787075,  1.59980519],
       [ 0.86966197, -0.75215469, -0.34291549, -1.23051925],
       [ 0.83290511,  0.04999722, -1.09717419,  0.88200421],
       [-0.21576541,  1.22733542, -0.38035024,  0.15422431]])

In [23]:
arr > 0

array([[False,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [False,  True, False,  True]])

In [25]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2,  2],
       [ 2, -2, -2, -2],
       [ 2,  2, -2,  2],
       [-2,  2, -2,  2]])

In [27]:
np.where(arr > 0, 2, arr)

array([[-1.72590478,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.75215469, -0.34291549, -1.23051925],
       [ 2.        ,  2.        , -1.09717419,  2.        ],
       [-0.21576541,  2.        , -0.38035024,  2.        ]])

In [31]:
arr = rng.standard_normal((5, 4))

In [33]:
arr

array([[-0.25705631, -1.10634059, -1.26454202,  0.31353636],
       [ 0.7705311 ,  1.18048147,  1.07562676, -0.481746  ],
       [-0.33536648,  1.06791011,  0.20971464,  1.78689513],
       [ 0.36199583, -0.11643202, -1.08540444,  0.90759802],
       [-0.0223753 , -0.52718365, -0.89262186,  0.83363717]])

In [35]:
arr.mean()

0.12094289692710518

In [37]:
np.mean(arr)

0.12094289692710518

In [39]:
arr.sum()

2.4188579385421036

In [41]:
arr.mean(axis=1)

array([-0.57860064,  0.63622333,  0.68228835,  0.01693935, -0.15213591])

In [43]:
arr.sum(axis=0)

array([ 0.51772885,  0.49843532, -1.95722691,  3.35992068])

In [45]:
arr = np.array([0,1,2,3,4,5,6,7])

In [47]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [53]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [59]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [65]:
mn = arr.argmin()

In [68]:
mn

0

In [70]:
mx = arr.argmax()
mx

8

In [72]:
mn = arr.min()
mn

0

In [74]:
mx = arr.max()
mx

8

In [80]:
arr = rng.standard_normal(100)
(arr > 0).sum()

49

In [82]:
(arr <= 0).sum()

51

In [86]:
bools = np.array([False, False, True, False])
bools.any()

True

In [88]:
bools.all()

False

In [90]:
arr = rng.standard_normal(6)

In [92]:
arr

array([-0.46531168,  0.33677547,  2.43570851,  0.08227637,  0.56869484,
       -0.30109289])

In [94]:
arr.sort()

In [96]:
arr

array([-0.46531168, -0.30109289,  0.08227637,  0.33677547,  0.56869484,
        2.43570851])

In [98]:
arr = rng.standard_normal((5, 3))

In [100]:
arr

array([[-0.93135085, -0.37513071, -0.99370085],
       [ 0.55333413, -0.73700989,  0.20666909],
       [ 0.44863988,  0.38669038, -0.1034086 ],
       [-2.48161223,  1.67118674,  1.89710163],
       [-1.88958158,  0.04035275, -0.95489212]])

In [102]:
arr.sort(axis=0)

In [104]:
arr

array([[-2.48161223, -0.73700989, -0.99370085],
       [-1.88958158, -0.37513071, -0.95489212],
       [-0.93135085,  0.04035275, -0.1034086 ],
       [ 0.44863988,  0.38669038,  0.20666909],
       [ 0.55333413,  1.67118674,  1.89710163]])

In [106]:
arr.sort(axis=1)

In [108]:
arr

array([[-2.48161223, -0.99370085, -0.73700989],
       [-1.88958158, -0.95489212, -0.37513071],
       [-0.93135085, -0.1034086 ,  0.04035275],
       [ 0.20666909,  0.38669038,  0.44863988],
       [ 0.55333413,  1.67118674,  1.89710163]])

In [110]:
arr2 = np.array([5, -10, 7, 1, 0, -3])

In [112]:
sorted_arr2 = np.sort(arr2)
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

In [114]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

In [120]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [124]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [128]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [132]:
arr = np.arange(10)
np.save("some_array", arr)

In [138]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [144]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [148]:
x @ np.ones(3)

array([ 6., 15.])

In [150]:
from numpy.linalg import inv, qr

In [152]:
X = rng.standard_normal((5, 5))

In [154]:
mat = X.T @ X

In [156]:
inv(mat)

array([[ 0.21003156,  0.11139432, -0.05759122,  0.06990594,  0.02651067],
       [ 0.11139432,  0.82798972,  0.11661833,  0.025371  , -0.16859686],
       [-0.05759122,  0.11661833,  0.83199997,  0.27955721,  0.00603516],
       [ 0.06990594,  0.025371  ,  0.27955721,  0.2479943 , -0.00930161],
       [ 0.02651067, -0.16859686,  0.00603516, -0.00930161,  0.27407069]])